version: '3'
services:
    postgres:
        image: postgres:16.2-bookworm
        restart: always
        # set shared memory limit when using docker-compose
        shm_size: 128mb
        volumes:
            # The volume for postgres data
            - ./postgres-data/:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: metapulse-db
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: 123
    spring-app:
        build:
            context: .
        container_name: spring-app
        ports:
            - "8080:8080"
        volumes:
            # The volume for the code
            - .:/workspace:cached
        # command: /bin/bash -c "cd /workspace && ./gradlew bootRun"
        command: /bin/bash -c "cd /workspace && while true; do sleep 3600; done"
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/metapulse-db
            SPRING_DATASOURCE_USERNAME: admin
            SPRING_DATASOURCE_PASSWORD: 123